name: Sub-Store
description: 高级订阅管理工具
icon: https://raw.githubusercontent.com/cc63/ICON/main/Sub-Store.png
compat_arguments:
  cors: "https://sub-store.vercel.app,http://substore.stash,https://substore.stash"
compat_arguments_desc: |
  脚本超时(Egern 有问题, 不支持自定义, 本文件中固定为 900 秒)

  1️⃣ cors

  允许浏览器跨域访问 Sub-Store 后端的 origin.
  默认为 https://sub-store.vercel.app,http://substore.stash,https://substore.stash.
  多个用 , 连接.

  设为 * 可恢复旧的任意来源访问行为, 存在钓鱼网站读取配置的风险

scriptings:
  - http_request:
      name: Sub-Store Core
      match: ^https?:\/\/sub\.store\/((download)|api\/(preview|(utils\/node-info)))
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-1.min.js
      body_required: true
      max_size: 999999999
      timeout: 900
      arguments:
        _compat.$argument: "cors={{{cors}}}"
  - http_request:
      name: Sub-Store Simple
      match: ^https?:\/\/sub\.store
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-0.min.js
      body_required: true
      max_size: 999999999
      timeout: 900
      arguments:
        _compat.$argument: "cors={{{cors}}}"
mitm:
  hostnames:
    includes:
      - sub.store
